# Generated by Django 4.0.1 on 2022-01-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('1', 'Type 1'), ('2', 'Type 2'), ('3', 'Type 3')], max_length=5)),
                ('description', models.CharField(max_length=1000)),
                ('value', models.IntegerField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
