# Generated by Django 4.0.1 on 2022-01-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='comment',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
