# Generated by Django 4.0.1 on 2022-02-15 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0)),
                ('path', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
            ],
        ),
    ]
