# Generated by Django 4.0.1 on 2022-02-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
